config/routes.rb
TrainApp::Application.routes.draw do
  match 'help' => 'application#help'

  match 'signup' => 'users#new'
  match 'signin' => 'sessions#new'
  match 'signout' => 'sessions#destroy'

  match 'password' => 'users#password', via: [:get]
  match 'password' => 'users#change_password', via: [:post]

  resources :users
  resources :posts, only: [:create]

  match 'follow' => 'relationships#create', via: [:post]
  match 'unfollow' => 'relationships#destory', via: [:delete]
  match 'followers' => 'relationships#followers', via: [:get]
  match 'followeds' => 'relationships#followeds', via: [:get]

  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'application#home'

end

app/models/user.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(30)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  remember_token  :string(255)
#  admin           :boolean
#

# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  # 这个是 rails 针对 mase-assignment 问题的白名单的解决办法
  # 将 password 与 password_confirmation 添加进入白名单, 是因为就算对这两个值进行了设置, 如果无法验证成功, 还是无法影响安全
  attr_accessible :email, :name, :password, :password_confirmation

  # 打开 secure_password.rb 查看后发现, 添加了 password_digest 的不为空检查, password 的 confirmation 检查, 所以
  # 这与我下面写的 "貌似只是自动添加了对 password_digest 为空的判断而已.." 并没有错.
  # 这个方法的作用, 有两个:
  #  1. 在为用户设置密码的时候(password=), 自动将没有加密的函数进行加密, 设置给 password_digest
  #  2. 添加用户的 authenticate 方法, 输入没有加密的密码, 其自动根据 password_digest 进行解密, 与密码比对
  has_secure_password

  # 向 Model 注册回掉函数有主要有两种方式
  # 1. 直接通过 before_save 注册一个 &block
  # 2. 使用 symbol 注册回掉函数的方法名
  before_save { |user| user.email = user.email.downcase }
  before_save :create_remember_token

  before_destroy :admin_check

  validates :email, presence: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}, uniqueness: {case_sensitive: false}
  validates :name, presence: true, length: {maximum: 30}

  # has_secure_password 文档中说,自动添加了 password, password_confirmation 但貌似是自动添加了对 password_digest 为空的判断而已...
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true

  has_many :posts

  # 当前用户跟踪了很多人.
  # 将用户的跟踪分为 "跟踪者(follower) 与被跟踪者(followed)", 这里需要的关系是 N-N ,所以使用
  # has_many :through 来完成.  由于 follower 与 followed 的关系记录在 relationship 表中,
  # 所以需要通过 through: :relationship 来完成中间表的关联.
  # 默认情况下, 如果指定 foreign_key, 那么 User has_many relationships, 那么:
  # 1. 外键存储在 "多" 的一端
  # 2. 外键的名字为 user_id, 代表 relationships 通过 user_id 找到其关联的那一个 user
  # 由于现在 relationships 表中没有 user_id, 只有 follower_id 与 followed_id, 用来代表
  # 两个 user 之间的跟踪关系, 跟踪者的 id 与被跟踪者的 id, 并且这里需要寻找的是当前用户跟踪的人,
  # 也就是说, 在 relationships 表中, 当前用户是处于跟踪者的位置, 所以在 relationships 表中,
  # 当前用户寻找他的跟踪的人的时候, 是当前用户的 id 作为跟踪者的时候, 也就是 follower_id = user.id 的时候
  has_many :relationships, foreign_key: "follower_id"
  # 如果没有设置 source, 那么下面的语句则在通过 u.followeds 跟踪的用户的时候, 会
  # 到 relationships 表中通过与 relationships.followed/followeds 建立关系
  has_many :followeds, through: :relationships
  #has_many :followed_users, through: :relationships, source: "followed"

  # 当前用户被哪些用户跟踪
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship"
  has_many :followers, through: :reverse_relationships

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  # 是否跟了此人
  def following?(user)
    relationships.find_by_followed_id(user.id) != nil
  end

  # 返回自己与其他用户最新发布的 posts
  def feeds
    Post.where("user_id=? or user_id IN (?)", id, followed_ids)
  end

  def unfollow(user)
    # TODO 非常奇怪, 在 rails c 中, 可以使用 user.relationships.where("followed_id=?", 3)
    # 这样执行: SELECT `relationships`.* FROM `relationships` WHERE `relationships`.`follower_id` = 1 AND (followed_id=3)
    # 获取到 relationships, 可在 rspc 中则只有使用 dynamic finder 才有效果?
    #relationships.where("followed_id=?", user.id).destroy
    relationships.find_by_followed_id(user.id).destroy

    # 区别 where 与动态 find_by 方法

    # > u.relationships.where('followed_id=?', 3)
    # Relationship Load (0.4ms)  SELECT `relationships`.* FROM `relationships` WHERE `relationships`.`follower_id` = 1
    # AND (followed_id=3)

    # > u.relationships.find_by_followed_id(3)
    #  Relationship Load (0.5ms)  SELECT `relationships`.* FROM `relationships` WHERE `relationships`.`follower_id` = 1
    # AND `relationships`.`followed_id` = 3 LIMIT 1
  end

  # 修改密码
  def change_password(options)
    return false if not options.is_a?(Hash)
    authenticate(options[:oldpassword]) && update_attributes(options.except(:oldpassword))
  end

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  # 标记为管理员的用户不允许删除
  # 需要阻止在 destroy 继续执行, 返回 false 即可.
  # 同时可以将 erros 利用 add(:column, msg) 添加到 model.erros 中
  def admin_check
    errors.add(:admin, "只有非管理员可以被删除") if admin?
    !admin?
  end

end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  before_filter :require_login, only: [:edit, :update, :password, :change_password, :destroy]

  # 用户只能修改自己
  before_filter :correct_user, only: [:edit, :update]


  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "用户注册成功"
      redirect_to @user
    elsif
      # 重新使用 new.html 进行渲染
      # errors 信息被记录在了 user model 身上
    render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "修改成功"
      sign_in(@user, !session.key?(:remember_token))
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    if user.destroy
      flash[:success] = "用户 #{user.name} 删除成功"
      redirect_to user
    else
      render 'index'
    end
  end

  def password
    @user = current_user
  end

  def change_password
    @user = current_user
    if @user.change_password(params[:user])
      # 验证通过
      sign_in(@user, !session.key?(:remember_token))
      flash[:success] = "密码修改成功"
      redirect_to password_path
    else
      # 验证失败
      flash.now[:error] = "修改密码失败" if not @user.errors.any?
      render 'password'
    end
  end

  private
  def correct_user
    user = User.find(params[:id])
    unless current_user?(user)
      flash[:error] = "不允许修改其他人的信息"
      redirect_to(root_path)
    end
  end

end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
  # 通过 user 的 email 获取在 gravatar 的头像
  def gravatar_for(user, size=80, https=false)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    image_tag("http#{https ? "s://secure" : "://www"}.gravatar.com/avatar/#{gravatar_id}?s=#{size}", alt: user.name, class: 'gravatar')
  end
end

app/views/users/_overview.html.slim
h1
  = gravatar_for(user)
  = user.name.camelize

-unless current_user?(user)
  #follow_action
    / ajax, follow / unfollow
    - if current_user.following?(user)
      = render 'relationships/unfollow'
    - else
      = render 'relationships/follow'

app/views/users/_state.html.slim
h1
  = gravatar_for(current_user)
  = current_user.name.camelize
.row-fluid
  .span6
    a href=followeds_path Followed #{current_user.followeds.count} Users
  .span6
    a href=followers_path Have #{current_user.followers.count} Followers

app/views/users/_user_list.html.slim
- @users.each do |user|
  .user
    = gravatar_for(user, 60)
    = link_to user do
      i.icon-link &nbsp;
      = user.name
    - if current_user.admin?
      | &nbsp; | &nbsp;
      = link_to 'delete', user, method: :delete, data: { confirm: 'You sure?' }

app/views/users/edit.html.slim
h1.center Update your profile
.row
  .span6.offset3
    = render 'shared/model_errors', model: @user

    = form_for(@user) do |f|
      = f.label :name
      = f.text_field :name
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = f.submit "Save Changes", class: 'btn btn-large btn-primary'

    = gravatar_for(@user, 60)
    = link_to("change", 'http://gravatar.com/emails', target: '_blank')

app/views/users/index.html.slim
- provide(:title, 'Users Page')

h1.center All Users

= render 'shared/alert_errors'

.row.pagination-centered
  = paginate @users

.row
  .span4
    = render partial: 'overview', locals: {user: current_user}

  .span8
    - @users.each do |user|
      .user
        = gravatar_for(user, 60)
        = link_to user do
          i.icon-link &nbsp;
          = user.name
        - if current_user.admin?
          | &nbsp; | &nbsp;
          = link_to 'delete', user, method: :delete, data: { confirm: 'You sure?' }

.row.pagination-centered
  = paginate @users

app/views/users/new.html.slim
.row
  h2#title.alert.alert-info
    | 注册新用户

.row
  .span6.offset3
    = render 'shared/model_errors', model: @user

    = form_for(@user) do |f|
      = f.label :name
      = f.text_field :name
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation
      = f.submit "Create my account", class: 'btn btn-large btn-primary'

app/views/users/password.html.slim
h1.center Change Password

.row
  .span6.offset3
    = render 'shared/alert_errors'
    = render 'shared/model_errors', model: @user

    = form_for(@user, method: :post, url: password_url) do |f|
      = f.label :oldpassword, "Password"
      = f.password_field :oldpassword
      = f.label :password, "New Password"
      = f.password_field :password
      = f.label :password_confirmation, "Confirm"
      = f.password_field :password_confirmation
      = f.submit 'Change', class: 'btn btn-large btn-primary'

app/views/users/show.html.slim
= render 'shared/alert_errors'

.row
  .span4
    = render partial: 'overview', locals: { user: @user }

  .span8
    = render @posts
    = paginate @posts